package com.loftydevelopment.species_csv_to_wp.model.enum

enum class SpeciesGroup{
    AFRICAN_CICHLIDS,
    AMERICAN_CICHLIDS,
    ANGELFISH,
    AROWANA,
    BARBS,
    BETTAS,
    BICHIR,
    BRACKISH,
    CORY,
    DANIOS,
    DATNOID,
    DISCUS,
    EELS,
    GOLDFISH,
    GOURAMIS,
    HATCHETS,
    INVERTEBRATES,
    KILLIFISH,
    KNIFEFISH,
    KOI,
    LIVEBEARER,
    LOACHES,
    MISC,
    MISC_CATFISH,
    MONSTER,
    PLECOS,
    PUFFER,
    RAINBOWFISH,
    RASBORAS,
    SHARKS,
    SNAKEHEAD,
    SYNOS,
    TETRAS,
}
